### ISSUE TITLE
how to use this to write data to fitbit

### ISSUE THREAD

**Issue by gabrielconfused** [djchen/oauth2-fitbit#20]

**Comment by djchen** [comment]
Can you be more specific? Please provide snippets of code for what you are trying to do.

If you need general Fitbit API help, you can ask over at https://community.fitbit.com/t5/Web-API/bd-p/dev

**Comment by gabrielconfused** [comment]
I would like to write my water log data to fitbit.. I haven't seen any example wherein you are writing data to fitbit. Most examples are pulling data from fitbit

**Comment by djchen** [comment]
You can do this for example:

```
        $params = http_build_query(['fullname' => 'John Doe', 'aboutMe' => 'Setting a new one..']);
        $request = $provider->getAuthenticatedRequest(
            Fitbit::METHOD_POST,
            Fitbit::BASE_FITBIT_API_URL . '/1/user/-/profile.json',
            $accessToken,
            ['body' => $params, 'headers' => ['content-type' => 'application/x-www-form-urlencoded']]
        );
        $response = $provider->getResponse($request);
```

Not the cleanest thing since The PHP League's OAuth 2.0 client doesn't provide a whole lot of support for it. It's possible for this library to provide some conveniences to make that easier. Feel free to submit a PR if you are interested.

Alternatively you can use something like Unirest to make it cleaner and easier as well. After you get the access token, you only need to send it as part of the Authorization header. (ie "Authorization: Bearer " . $accessToken->getToken())
